name: cf_map_flutter
description: Comipara 7 Creator Booth Map Viewer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.5.3
  idb_shim: ^2.6.1
  collection: ^1.19.1
  http: ^1.2.2
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  umami_analytics: ^0.2.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - data/map.json
    - data/booth-proximity.json
    - data/catalog-initial.json
    - data/fandoms-initial.json
    - data/last-updated-initial.json
    - assets/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          

